### ISSUE TITLE
Is this what I'm looking for?

### ISSUE THREAD

**Issue by AtariBaby** [Awarua-/DCPlusPlusRlsAnnouncer#2]
Hi

I want to modify a GitHub project that, like sickbeard and other similar programs, pulls from usenet and torrents. But I want to modify a similar program to pull from dc++ instead of usenet. Is this what I'm looking for, and would I have permission to use it for such a project?

Thanks

**Comment by Awarua-** [comment]
This doesn't pull from dc++, it posts magnetic links to a dc++ channel when a client has downloaded something new.

It won't do what you have described and I don't know of any projects that have what you need. You could build your own using the dc++ protocol, but that would be a lot of effort.

But you have my permission to do whatever you like with this project.
